### ISSUE TITLE
Example snippet or theme using LiquidX? 

### ISSUE THREAD

**Issue by blanklob** [unshopable/liquidx#1]
### What type of change do you want to see?

New feature

### Overview

Do you have an example theme with snippets based on LiquidX syntax? I would love to try this out.

### Motivation

Something that I can instantly clone and launch development server. 

Thanks

**Comment by davidthorand** [comment]
@blanklob there you go: https://github.com/unshopable/melter/tree/main/examples/liquidx

**Comment by blanklob** [comment]
Thanks tried it great project, if only this was a Vite Plugin. Do you plan a Vite Plugin?

**Comment by davidthorand** [comment]
Created a new issue for that topic: https://github.com/unshopable/liquidx/issues/2

(Also closing this issue now)
